### ISSUE TITLE
Could you please upload the file 'Shepp_Logan_3d_512.dat'

### ISSUE THREAD

**Issue by xushuo0629** [leehoy/CTReconstruction#3]

**Comment by leehoy** [comment]
Hello, I'm sorry but I can't upload the phantom file due to the file size limit of Github.
You can create the phantom file using the phantom3d library which is based on Matlab and also works with Octave.

You can find the module at the following link, https://www.mathworks.com/matlabcentral/fileexchange/9416-3d-shepp-logan-phantom.

**Comment by xushuo0629** [comment]
thank u very much!

**Comment by xushuo0629** [comment]
> Hello, I'm sorry but I can't upload the phantom file due to the file size limit of Github.
> You can create the phantom file using the phantom3d library which is based on Matlab and also works with Octave.
> 
> You can find the module at the following link, https://www.mathworks.com/matlabcentral/fileexchange/9416-3d-shepp-logan-phantom.

thank u very much!
