### ISSUE TITLE
The function Filter.m is not defined

### ISSUE THREAD

**Issue by xysue2000** [leehoy/CTReconstruction#4]
In the function FanFilter.m, the function Filter.m is not defined.

**Comment by leehoy** [comment]
Hello, @xysue2000. I assume you're trying to use the FanFilterArc function. I'm sorry, I don't have the Filter.m file right now. Instead, I rewrote the FanFilterArc.m function without Filter.m. The filter is similar to the line filter with a minor modification. The new implementation is based on Kak's explanation. However, I haven't tested it since I don't have access to MATLAB. I apologize for the inconvenience.
